### ISSUE TITLE
Merge simplecss fork

### ISSUE THREAD

**Issue by RazrFalcon** [maps4print/azul#100]
Hi. I plan to revamp the `simplecss` crate, so if you have any requests - feel free to ask.

I see you added some new features [here](https://github.com/RazrFalcon/simplecss/compare/master...cubetastic33:master). Should we merge them?

**Comment by fschutt** [comment]
Sure, although it's not CSS 2.1 anymore - currently the only problem is that in my for `@thing { { } }` parses (while it shouldn't). It also needs more tests. But yeah, I didn't merge them originally because I thought you had given up on the crate.
