### ISSUE TITLE
Move to crates.io

### ISSUE THREAD

**Issue by Pzixel** [maps4print/azul#103]
WebRender has been released on crates.io: https://mozillagfx.wordpress.com/2019/01/10/webrender-newsletter-35/

Don't you mind to publish too?

**Comment by fschutt** [comment]
Did you read the sticky? It's not there yet, it's a half-finished project that breaks the API every few days - there's no point in publishing. And I'm not exactly in a hurry with publishing, especially not after #95 - it highly depends if cargo changes its version selection algorithm or sticks with the current one.
