### ISSUE TITLE
Hello world panics

### ISSUE THREAD

**Issue by mark-summerfield** [maps4print/azul#107]
## Description

I got this error message from the hello world example copy/pasted from the getting started page:

An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /home/mark/azhello/target/release/build/gleam-e6b84ff1ff1406f8/out/gl_bindings.rs at line 1497 in thread main

Error information:
gl function was not loaded

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn
std::panicking::rust_panic_with_hook @ panicking.rs:495
std::panicking::begin_panic
gleam::ffi_gl::missing_fn_panic
webrender::device::gl::Device::begin_frame
webrender::renderer::Renderer::new
azhello::main
std::rt::lang_start::{{closure}}
std::rt::lang_start_internal::{{closure}} @ rt.rs:59
std::panicking::try::do_call @ panicking.rs:310
 @ lib.rs:102
std::panicking::try @ panicking.rs:289
std::panic::catch_unwind @ panic.rs:398
std::rt::lang_start_internal @ rt.rs:58
unresolved function

## Version / OS

Xubuntu 18 64-bit

* azul version:

Just did git hub as docs say, but fresh install of rust + azul today in a VM.

* Operating system:

Xubuntu

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

I just did cargo run --release. The first hello world (with the println) worked fine.

**Comment by fschutt** [comment]
Well, for some reason you don't seem to have OpenGL installed or a very old version of OpenGL that isn't compatible with OpenGL 3.1 (or OpenGL ES 2.0). Some necessary OpenGL functions couldn't be loaded.

What does `glxinfo` output?

**Comment by mark-summerfield** [comment]
I'm just running it in virtualbox but I did the apt get etc stated beforehand. Here's the glxinfo:

name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: Chromium
server glx version string: 1.3 Chromium
server glx extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
client glx vendor string: Chromium
client glx version string: 1.3 Chromium
client glx extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
GLX version: 1.3
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
OpenGL vendor string: Humper
OpenGL renderer string: Chromium
OpenGL version string: 2.1 Chromium 1.9
OpenGL shading language version string: 1.30
OpenGL extensions:
    GL_ARB_depth_texture, GL_ARB_draw_buffers, GL_ARB_fragment_program, 
    GL_ARB_fragment_shader, GL_ARB_multisample, GL_ARB_multitexture, 
    GL_ARB_occlusion_query, GL_ARB_pixel_buffer_object, 
    GL_ARB_point_parameters, GL_ARB_point_sprite, GL_ARB_shader_objects, 
    GL_ARB_shader_texture_lod, GL_ARB_shading_language_100, GL_ARB_shadow, 
    GL_ARB_texture_border_clamp, GL_ARB_texture_compression, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_float, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_transpose_matrix, 
    GL_ARB_vertex_buffer_object, GL_ARB_vertex_program, GL_ARB_vertex_shader, 
    GL_ARB_window_pos, GL_CR_bounding_box, GL_CR_cursor_position, 
    GL_CR_head_spu_name, GL_CR_performance_info, GL_CR_print_string, 
    GL_CR_readback_barrier_size, GL_CR_saveframe, GL_CR_server_id_sharing, 
    GL_CR_server_matrix, GL_CR_state_parameter, GL_CR_synchronization, 
    GL_CR_tile_info, GL_CR_tilesort_info, GL_CR_window_size, 
    GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_compiled_vertex_array, GL_EXT_draw_range_elements, 
    GL_EXT_fog_coord, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
    GL_EXT_multi_draw_arrays, GL_EXT_secondary_color, GL_EXT_shadow_funcs, 
    GL_EXT_stencil_two_side, GL_EXT_stencil_two_side, GL_EXT_stencil_wrap, 
    GL_EXT_texture3D, GL_EXT_texture_compression_s3tc, 
    GL_EXT_texture_cube_map, GL_EXT_texture_edge_clamp, 
    GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
    GL_EXT_texture_env_dot3, GL_EXT_texture_filter_anisotropic, 
    GL_EXT_texture_lod_bias, GL_EXT_texture_object, GL_EXT_texture_rectangle, 
    GL_EXT_texture_sRGB, GL_IBM_rasterpos_clip, 
    GL_IBM_texture_mirrored_repeat, GL_NV_fog_distance, 
    GL_NV_texgen_reflection, GL_NV_texture_rectangle, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_border_clamp, GL_SGIS_texture_edge_clamp

1 GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  32  0 r  y y   8  8  8  8 .  .  0 24  8 16 16 16 16  0 0 None

1 GLXFBConfigs:
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8  0  0  0  0  1 1 None

**Comment by fschutt** [comment]
You probably need to install `libgles2-mesa-dev` to run it in VirtualBox. See the required system dependencies for Linux: https://github.com/maps4print/azul/wiki/Installation#system-dependencies-linux-only

**Comment by mark-summerfield** [comment]
I installed that but it still give this error:

An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /home/mark/azhello/target/release/build/gleam-e6b84ff1ff1406f8/out/gl_bindings.rs at line 1497 in thread main

Error information:
gl function was not loaded

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn
std::panicking::rust_panic_with_hook @ panicking.rs:495
std::panicking::begin_panic
gleam::ffi_gl::missing_fn_panic
webrender::device::gl::Device::begin_frame
webrender::renderer::Renderer::new
azhello::main
std::rt::lang_start::{{closure}}
std::rt::lang_start_internal::{{closure}} @ rt.rs:59
std::panicking::try::do_call @ panicking.rs:310
 @ lib.rs:102
std::panicking::try @ panicking.rs:289
std::panic::catch_unwind @ panic.rs:398
std::rt::lang_start_internal @ rt.rs:58
unresolved function

Here is the glxinfo:

name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: Chromium
server glx version string: 1.3 Chromium
server glx extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
client glx vendor string: Chromium
client glx version string: 1.3 Chromium
client glx extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
GLX version: 1.3
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_texture_from_pixmap, GLX_SGIX_fbconfig
OpenGL vendor string: Humper
OpenGL renderer string: Chromium
OpenGL version string: 2.1 Chromium 1.9
OpenGL shading language version string: 1.30
OpenGL extensions:
    GL_ARB_depth_texture, GL_ARB_draw_buffers, GL_ARB_fragment_program, 
    GL_ARB_fragment_shader, GL_ARB_multisample, GL_ARB_multitexture, 
    GL_ARB_occlusion_query, GL_ARB_pixel_buffer_object, 
    GL_ARB_point_parameters, GL_ARB_point_sprite, GL_ARB_shader_objects, 
    GL_ARB_shader_texture_lod, GL_ARB_shading_language_100, GL_ARB_shadow, 
    GL_ARB_texture_border_clamp, GL_ARB_texture_compression, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_float, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_transpose_matrix, 
    GL_ARB_vertex_buffer_object, GL_ARB_vertex_program, GL_ARB_vertex_shader, 
    GL_ARB_window_pos, GL_CR_bounding_box, GL_CR_cursor_position, 
    GL_CR_head_spu_name, GL_CR_performance_info, GL_CR_print_string, 
    GL_CR_readback_barrier_size, GL_CR_saveframe, GL_CR_server_id_sharing, 
    GL_CR_server_matrix, GL_CR_state_parameter, GL_CR_synchronization, 
    GL_CR_tile_info, GL_CR_tilesort_info, GL_CR_window_size, 
    GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_compiled_vertex_array, GL_EXT_draw_range_elements, 
    GL_EXT_fog_coord, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
    GL_EXT_multi_draw_arrays, GL_EXT_secondary_color, GL_EXT_shadow_funcs, 
    GL_EXT_stencil_two_side, GL_EXT_stencil_two_side, GL_EXT_stencil_wrap, 
    GL_EXT_texture3D, GL_EXT_texture_compression_s3tc, 
    GL_EXT_texture_cube_map, GL_EXT_texture_edge_clamp, 
    GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
    GL_EXT_texture_env_dot3, GL_EXT_texture_filter_anisotropic, 
    GL_EXT_texture_lod_bias, GL_EXT_texture_object, GL_EXT_texture_rectangle, 
    GL_EXT_texture_sRGB, GL_IBM_rasterpos_clip, 
    GL_IBM_texture_mirrored_repeat, GL_NV_fog_distance, 
    GL_NV_texgen_reflection, GL_NV_texture_rectangle, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_border_clamp, GL_SGIS_texture_edge_clamp

1 GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  32  0 r  y y   8  8  8  8 .  .  0 24  8 16 16 16 16  0 0 None

1 GLXFBConfigs:
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8  0  0  0  0  1 1 None

**Comment by fschutt** [comment]
You have OpenGL 1.3 installed (which is the default OpenGL version that X11 comes with, but it's very old) - azul requires OpenGL 3.0 or higher. Your glxinfo shows:

```
server glx version string: 1.3 Chromium
client glx version string: 1.3 Chromium
GLX version: 1.3
OpenGL version string: 2.1 Chromium 1.9
OpenGL shading language version string: 1.30
```

Here is my VirtualBox VM with the versions it should show (all demos run fine on this system):

![image](https://user-images.githubusercontent.com/12084016/52562168-eac0f200-2dfd-11e9-8666-66f03583a914.png)

Since we both have identical VMs with the only difference being XUbuntu versus regular Ubuntu, there seems to be a package that I have installed that you don't. Try the following, one by one and see if it helps:

```sh
sudo apt install libegl1
sudo apt install libgles1
sudo apt install libgles2
sudo apt install libgles2-mesa
sudo apt install libgles2-mesa-dev
sudo apt install mesa-common mesa-common-dev
```

Test after each package if it works. I am not sure which package is actually responsible for actually drawing the graphics, that's always a problem under Linux since there are so many similarly-named packages, so it's more trial and error than anything. I originally assumed that `libgles-mesa-dev` would take care of this, but that doesn't seem to be the case.

What version of XUbuntu are you running, what are your upstream mirrors, what does `apt list --installed` show (to see what packages you have installed, in order to compare it with mine), do you run X11 or Wayland? Thanks and sorry for the inconvenience.

**Comment by mark-summerfield** [comment]
libegl1, libgles1, libgles2, all already installed.
libgles2-mesa wasn't installed but didn't help when installed
[list.txt.gz](https://github.com/maps4print/azul/files/2851428/list.txt.gz)
.
libgles2-mesa-dev already installed.
mesa-common doesn't exist.
mesa-common-dev wasn't installed but didn't help when installed.

I've attached app list --installed as list.txt.gz (I think).

**Comment by mark-summerfield** [comment]
I finally realised what the problem was. In the VirtualBox settings I'd checked [X] Enable 3D Acceleration. I _unchecked_ it and then glxinfo told me (with 90% elided):
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.1 Mesa 18.2.2
OpenGL shading language version string: 1.40
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

So now I get the Azul App with a white resizable window and can continue to learn azul.

Thanks for all your help.
