### ISSUE TITLE
Counter example small issue + doc error

### ISSUE THREAD

**Issue by mark-summerfield** [maps4print/azul#112]
## Description

(1) On Xubuntu in a VM when I run the counter eg the window starts as a black rect, then clears to show a horizontal line (label above, 'button' below) but does _not_ show the counter or the button text. As soon as I click or resize both are shown correctly.

(2) In the counter docs the import is first shown as this:
```
use azul::{prelude::*, widgets::{label::Label, button::Button}};
```
which works.

However, later on (at the start of the Handling Callbacks section) the import is shown as:
```
use azul::prelude::*;
use azul::widgets::*;
```
which does _not_ work. So this is just a doc error.

## Version / OS

* azul version:

git latests

* Operating system:

Xubuntu
* Windowing system (X11 or Wayland, Linux only):

**Comment by fschutt** [comment]
I've fixed the documentation error, but the text not showing is the same as #65, so I'd avoid duplicating the issue.
