### ISSUE TITLE
Fonts not rendering under Linux

### ISSUE THREAD

**Issue by fschutt** [maps4print/azul#125]
## Description

HarfBuzz currently returns spaces instead of glyph indices for any font if the application is running on Linux. This is probably not a problem of Azul, this should be reported to HarfBuzz developers.

## Version / OS

* azul version: https://github.com/maps4print/azul/commit/efaedc0790d761720ff3a7b89775a5c023a95652

* Operating system: Ubuntu 17.04

* Windowing system (X11 or Wayland, Linux only): X11, Unity

## Steps to Reproduce

Run the calculator example on Linux and see that the font on the buttons isn't loading

## Additional Information

Note that the memory usage for any project that doesn't use fonts is very low (< 20MB versus a the "normal" 40MB). This is an indicator that WebRender uses a huge amount of memory for font rendering (often 10MB per font!). This should be reported and fixed in WebRender.

**Comment by tarriel** [comment]
I seem to be having the same problem, are there any work arounds?

**Comment by fschutt** [comment]
No, it's a problem with harfbuzz, has to be reported to the harfbuzz maintainers. Haven't found the time to do so yet.

**Comment by Stoeoef** [comment]
A call to `hb_ot_font_set_funcs(new_hb_font)`  for a newly created harfbuzz font solves the issue.

Like this (See text_shaping.rs):
```rust
        let hb_font = unsafe { hb_font_create(hb_face) };
        unsafe { hb_ot_font_set_funcs(hb_font) };
```
[This](https://harfbuzz.github.io/harfbuzz-hb-ot-font.html) indicates that this method should be called by default, but well, I guess it isn't...
I hope that helps to narrow down the problem!
