### ISSUE TITLE
TextInput not redrawing on text input

### ISSUE THREAD

**Issue by kurtlawrence** [maps4print/azul#127]
## Description
TextInput is not redrawing screen on text input event. If another event fires afterwards, text is drawn.

## Version / OS

* azul version: 83a25ba5755b19fae683a33c9a3fc7007120b218

* Operating system: Windows

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce
Run `cargo run --example text_input`. Get focus on text input and type a _single_ character. It will not redraw. Typing another character will redraw (only showing the _first_ character). Moving mouse or making another event fire seems to redraw.

**Comment by fschutt** [comment]
This is fixed in https://github.com/maps4print/azul/commit/3c3feac8e7ea2eafacd5d3e2c03f6030038f773d - likely because the window wouldn't redraw when there were no window events.
