### ISSUE TITLE
Wiki Counter application misses first click

### ISSUE THREAD

**Issue by vitalije** [maps4print/azul#128]
## Description
In the Wiki example `CounterApplication` application doesn't update counter on first click. The only change I made is setting initially `CounterApplication { counter: 6 }` instead of the original 
`CounterApplication { counter: 0 }` given in the example. After compilation, application started
and displayed value 6. But after first click in the "update" button, label remains at 6. After second click it changes to 7, and on every following click it increases counter.

## Version / OS
Ubuntu 18.04 64bit

* azul version: latest commit

* Operating system:

* Windowing system X11

## Steps to Reproduce
my full code
```
extern crate azul;

use azul::{prelude::*, widgets::{label::Label, button::Button}};

struct CounterApplication {
    counter: usize,
}

impl Layout for CounterApplication {
    fn layout(&self, _info: LayoutInfo<Self>) -> Dom<Self> {
        let label = Label::new(format!("{}", self.counter)).dom();
        let button = Button::with_label("Update counter").dom()
            .with_callback(On::MouseUp, Callback(update_counter));

        Dom::new(NodeType::Div)
            .with_child(label)
            .with_child(button)
    }
}

fn update_counter(app_state: &mut AppState<CounterApplication>, _info: &mut CallbackInfo<CounterApplication>) -> UpdateScreen {
    app_state.data.modify(|state| state.counter += 1);
    Redraw
}

fn main() {
    let mut app = App::new(CounterApplication { counter: 6 }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
```
I hope that you don't mind me reporting this kind of issues. I am just looking at this library and trying to make first steps both in rust language and in azul library.

Vitalije

PS: I just discovered that the resizing window after first click will show the increased value, but then next click won't show result. It looks like clicking the button doesn't update display. Display gets updated later.

**Comment by fschutt** [comment]
I know, but I'm closing for now because this as this is the same issue as #127 (to avoid duplicate bug reports). It's just that the display doesn't immediately redraw, the click itself does get registered.
