### ISSUE TITLE
Wiki not up to date when it comes to Rust version required

### ISSUE THREAD

**Issue by StyMaar** [maps4print/azul#129]
I'm sorry to post an issue and not a PR for such a simple stuff, but I just don't know how to make a PR for github wikis.

[here](https://github.com/maps4print/azul/wiki/Installation) the required version of Rust hasn't been updated:
> Azul (version 0.1.0) is supported on Rust 1.28 or newer.

Azul now requires 1.33, and the Readme should be updated accordingly.

**Comment by StyMaar** [comment]
But why is there a «bug» label on this issue :( ? I'm sorry if I'm messing with your issue tracking …

**Comment by fschutt** [comment]
Fixed. It requires 1.31 though, not 1.33. Yeah, I know you can't make issues for wikis. The "bug" label is just because of the template you chose, it's not really that important. Thanks for reporting.
