### ISSUE TITLE
MacOs Build Error, Harfbuzz

### ISSUE THREAD

**Issue by JoeHowarth** [maps4print/azul#130]
## Description
Build error with Harfbuzz dependency

error: failed to run custom build command for `harfbuzz-sys v0.3.0 (https://github.com/maps4print/azul-dependencies?rev=c1548977fb62399f39aa642d2e7e24a24a25246e#c1548977)`
process didn't exit successfully: `/Users/jh/Desktop/projects/rust-proj/azul-play/azul/target/debug/build/harfbuzz-sys-9d1aa62a78f43bdf/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=HARFBUZZ_SYS_NO_PKG_CONFIG
touch -r harfbuzz/configure harfbuzz/configure.ac harfbuzz/m4/ax_check_link_flag.m4 harfbuzz/m4/ax_code_coverage.m4 harfbuzz/m4/ax_pthread.m4 harfbuzz/m4/gtk-doc.m4 harfbuzz/m4/libtool.m4 harfbuzz/m4/ltoptions.m4 harfbuzz/m4/ltsugar.m4 harfbuzz/m4/ltversion.m4 harfbuzz/m4/lt~obsolete.m4 harfbuzz/aclocal.m4 harfbuzz/configure harfbuzz/config.h.in harfbuzz/Makefile.am harfbuzz/Makefile.in harfbuzz/docs/Makefile.am harfbuzz/docs/Makefile.in harfbuzz/src/Makefile.am harfbuzz/src/Makefile.in harfbuzz/src/Makefile.sources harfbuzz/test/Makefile.am harfbuzz/test/Makefile.in harfbuzz/util/Makefile.am harfbuzz/util/Makefile.in harfbuzz/util/Makefile.sources harfbuzz/src/hb-ucdn/Makefile.am harfbuzz/src/hb-ucdn/Makefile.in harfbuzz/src/hb-ucdn/Makefile.sources harfbuzz/test/api/Makefile.am harfbuzz/test/api/Makefile.in harfbuzz/test/fuzzing/Makefile.am harfbuzz/test/fuzzing/Makefile.in harfbuzz/test/shaping/Makefile.am harfbuzz/test/shaping/Makefile.in harfbuzz/test/subset/Makefile.am harfbuzz/test/subset/Makefile.in harfbuzz/test/shaping/data/Makefile.am harfbuzz/test/shaping/data/Makefile.in harfbuzz/test/subset/data/Makefile.am harfbuzz/test/subset/data/Makefile.in harfbuzz/test/subset/data/Makefile.sources harfbuzz/test/shaping/data/in-house/Makefile.am harfbuzz/test/shaping/data/in-house/Makefile.in harfbuzz/test/shaping/data/in-house/Makefile.sources harfbuzz/test/shaping/data/text-rendering-tests/Makefile.am harfbuzz/test/shaping/data/text-rendering-tests/Makefile.in harfbuzz/test/shaping/data/text-rendering-tests/Makefile.sources harfbuzz/gtk-doc.make
cd /Users/jh/Desktop/projects/rust-proj/azul-play/azul/target/debug/build/harfbuzz-sys-1b3decccf0d0b22c/out && /Users/jh/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/c154897/harfbuzz-sys-0.3.0/harfbuzz/configure --prefix=/Users/jh/Desktop/projects/rust-proj/azul-play/azul/target/debug/build/harfbuzz-sys-1b3decccf0d0b22c/out --host=x86_64-apple-darwin --enable-static --disable-shared --without-icu --without-freetype --without-glib \
		CFLAGS="-fPIC -g" CXXFLAGS="-fPIC -g" CPPFLAGS=""

--- stderr
/bin/sh: /Users/jh/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/c154897/harfbuzz-sys-0.3.0/harfbuzz/configure: Permission denied
make: *** [all] Error 126
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()', /Users/jh/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/c154897/harfbuzz-sys-0.3.0/build.rs:28:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

## Version / OS

* azul version:
704abd8166a8ba40589166336830049e35c4ff0f

* Operating system:
MacOS 10.14.3 (18D109)

* Windowing system (X11 or Wayland, Linux only):
unknown

## Steps to Reproduce

git clone ...
cargo build

## Additional Information
Happens when trying to build repo or include repo as per wiki instructions
Same error for multiple commits

**Comment by fschutt** [comment]
Yeah I know, same error as on Linux - the error is basically "`./configure: Permission denied`", maybe try running it with sudo (i.e. `sudo cargo build`). Maybe that can work.

It seems that this is because the build script for harfbuzz [uses different execution paths](https://github.com/maps4print/azul-dependencies/blob/master/harfbuzz-sys-0.3.0/build.rs#L28-L42) on Windows vs Linux / Mac.

**Comment by JoeHowarth** [comment]
Yeah I tried `sudo cargo build` but it had no effect unfortunately
