### ISSUE TITLE
CMake dependency

### ISSUE THREAD

**Issue by Malfeasant** [maps4print/azul#134]
Is CMake meant to be a prerequisite for all systems?  It's mentioned in the wiki (Installation) but for "Linux only".  However, building on Windows fails without it as well.

**Comment by fschutt** [comment]
Yes, CMake is necessary for all systems, I've [fixed it by updating the wiki](https://github.com/maps4print/azul/wiki/Installation/_compare/bdbf59ae6b3ffcd773320b63c6be3f7d742f66ae...e27c8efe54b9a0db1e8661c8e803e95a6a28ad10)
