### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by Hero9909** [maps4print/azul#136]
## Description
currently the logging is just one line witch spams the stdout after every frame with th same line 

Logging should provide nessesary information about the current application and its states. therefor the code should contain a lot more options to turn on and off logging and log levels.

this would improve the developer experience as issues could be traced down easier.

## Are there alternatives or drawbacks?

ther might be better solutions but i could not list them , maybe there are some crates , providing ready to use implementations

## Is this a breaking change
this feature wont require changes on the user ( of azul ) side

## Additional notes
take this as an long term goal as this require an rework and some design decisions to find the best crate or the best format to enshure readability

**Comment by fschutt** [comment]
> currently the logging is just one line witch spams the stdout after every frame with th same line

This isn't "logging", I just forgot to remove a println. This will obviously be removed before a release.

> the code should contain a lot more options to turn on and off logging and log levels

You can already do this, look at the `AppConfig` struct from which you create the `App`. Not sure if this fixes your problem.

**Comment by Hero9909** [comment]
okay found what you said , nevermind.
Keep going if ive got enaught time ill try to add a chapter to README.md
