### ISSUE TITLE
Windows 10 build Error Harfbuzz

### ISSUE THREAD

**Issue by BIMSOMS** [maps4print/azul#137]
## Description
created azul hello world as per documentation.
build fails with this error: linking with `link.exe` failed: exit code: 1181
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOM...
....
= note: Non-UTF-8 output: LINK : fatal error LNK1181: Eingabedatei \"harfbuzz.lib\" kann nicht ge\xf6ffnet werden.\r\n

## Version / OS

* azul version:
azul v0.1.0 (https://github.com/maps4print/azul#e805c1c0)

* Operating system:
Windows 10
Version	10.0.17763 Build 17763

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

Start with a blank "hello_world" rust project.
Adding dependency `azul = { git = "https://github.com/maps4print/azul }` in cargo.toml builds fine.
Entering `extern crate azul;` in main.rs makes the build crash

## Additional Information

C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe

stable-x86_64-pc-windows-msvc toolchain
Visual Studio Code

**Comment by lzurbriggen** [comment]
You probably need to install [CMake ](https://cmake.org/download/) (required to build harfbuzz).

See https://github.com/maps4print/azul/wiki/Installation
> You currently need to install CMake before you can use azul. This applies to all platforms, since CMake is used during the build process to compile servo-freetype and harfbuzz-sys

**Comment by BIMSOMS** [comment]
nope. CMake was already installed. 

######################
C:\ProjectData\Develop\rust_test\azul_test\my_first_azul_app> cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory tore-generate its build system.

Run 'cmake --help' for more information.
##########################

Anything I need to configure?

**Comment by lzurbriggen** [comment]
I don't think I can help you any further, I just had a similar error on my first build and I forgot to install cmake, that fixed it for me.
I'm in almost exactly the same environment, just on the nightly toolchain (`nightly-x86_64-pc-windows-msvc`) and cmake 3.14.1.

**Comment by BIMSOMS** [comment]
just tried it out on another computer and it worked with stable toolchain.
I'll find out the difference and let you know.

**Comment by BIMSOMS** [comment]
Found it.
with "cargo build --verbose" there appeared an argument "-L native=C:\msys64\usr\bin", which was weird for building an msvc toolchain.
I had an old installation of mingw64 and GDK with some environment variables pointing to C:\msys64\...
Removing the environment variables that started with GDK_ and the Path references to the folder fixed it.

The bad news, I can't reproduce it. 
After uninstalling msys and gdk and re-installing the error doesn't come up anymore.
(Which is good news for anyone installing the current mingw.)

I'm not really king of config, but I assume there's a way to tell rustc not to search in c:\msys if the toolchain is msvc...
