### ISSUE TITLE
Error Building release

### ISSUE THREAD

**Issue by Hero9909** [maps4print/azul#138]
in release this line prevents usage of std::time::Instant

https://github.com/maps4print/azul/blob/71ab75c50e6d7443e11438c0ca8fac687224dbfd/azul/src/app.rs#L7

used on line 

https://github.com/maps4print/azul/blob/71ab75c50e6d7443e11438c0ca8fac687224dbfd/azul/src/app.rs#L389

used to measure remaining time.
Greetings

**Comment by fschutt** [comment]
Yeah, this has been fixed already. Update your `rev = "..."` field in your Cargo.toml file:

```toml
azul = { git = "https://github.com/maps4print/azul", rev = "e805c1c0372c7b73f14306d4ae33b00dbc107ba3" };
```
