### ISSUE TITLE
Problems with the Hello World Counter app (Display not refreshed)

### ISSUE THREAD

**Issue by reisub0** [maps4print/azul#139]
## Version / OS: Arch Linux

* azul version: 0.1.0

* Operating system: Arch Linux

* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce

1. Copy paste the text from the hello world from the README into a new cargo project
2. Fix the few compilation errors and missing modules that arise.
```rust
extern crate azul;

use azul::{
    prelude::*,
    widgets::{button::Button, label::Label},
};

struct DataModel {
    counter: usize,
}

impl Layout for DataModel {
    // Model renders View
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        let label = Label::new(format!("{}", self.counter)).dom();
        let button = Button::with_label("Update counter")
            .dom()
            .with_callback(On::MouseUp, Callback(update_counter));

        Dom::new(NodeType::Div).with_child(label).with_child(button)
    }
}

// View updates Model
fn update_counter(
    app_state: &mut AppState<DataModel>,
    _event: &mut CallbackInfo<DataModel>,
) -> UpdateScreen {
    app_state.data.modify(|state| state.counter += 1);
    Redraw
}

fn main() {
    let mut app = App::new(DataModel { counter: 0 }, AppConfig::default()).unwrap();
    let window = app
        .create_window(WindowCreateOptions::default(), css::native())
        .unwrap();
    app.run(window).unwrap();
}
```
3. `cargo run`
4. Hold the mouse really steady and make a single click on the bottom button.

#### The counter is not updated until you generate a new mouse event by moving the mouse a tiny bit or clicking again.

This means that the view is 1 step behind the model and not in sync with it.

**Comment by shadeofgod** [comment]
I too have the same issue here in Windows 10 with exact same code.

**Comment by X-m7** [comment]
The calculator example also has this same issue. Fortunately, an apparent fix in this counter app at least is to simply replace On::MouseUp with On::MouseDown. Not sure if that will have any other side effects, I haven't seen any when I tried it.

**Comment by reisub0** [comment]
@X-m7. that works because when you unclick the mouse (MouseUp event is generated) it generates a new event which provides that event to refresh the view. 
The problem is that the view isn't in sync with the model, which is what is supposed to be guaranteed by the framework at every frame.
Moreover, most buttons everywhere work with a MouseUp logic as opposed to a MouseDown logic to give the user the option to reconsider (I'm talking the send mail button in Gmail)

**Comment by fschutt** [comment]
The view is in sync, the display just doesn't get refreshed. It's also why `:hover` is currently slightly broken. The example code is correct, it's the framework that is wrong. The reason for this bug is that event handling got refactored during the changes that enable multi-window handling.

**Comment by reisub0** [comment]
@fschutt Thank you for clarifying and thank you for your work on this project.

**Comment by rockisch** [comment]
Just adding some info, seems like this is not the only issue with refreshing. When using hot_reloading, the style is also only updating when a new event is triggered.

**Comment by ironhouzi** [comment]
I am still having this exact same issue on Arch Linux, X11 and Azule commit ce29f269d17bfa73b879443d81d9dc1f387bd112
