### ISSUE TITLE
Unexpected panic when creating App instance.

### ISSUE THREAD

**Issue by rockisch** [maps4print/azul#147]
## Description
I'm getting an error whenever I try to create an App instance.

## Version / OS
* Azul version: 0.1.0

* Operating system: 5.0.6 Arch Linux

* Windowing system (X11 or Wayland, Linux only): Sway (Wayland Tiling WM)

## Steps to Reproduce
The program is panicking with the message ``called `Option::unwrap()` on a `None` value`` whenever I try to create an App instance.

Here's a minimal code, which is crashing in my system:

```
extern crate azul;

use azul::prelude::*;

struct MyDataModel { }

impl Layout for MyDataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        Dom::div()
    }
}

fn main() {
    let app = App::new(MyDataModel { }, AppConfig::default());
}
```

Backtrace:
[error.log](https://github.com/maps4print/azul/files/3056776/error.log)

**Comment by fschutt** [comment]
This is a Wayland-specific bug because Wayland can't call the `get_current_monitor()` before the Window is shown for some reason. Try running it via X11 by using an environment variable: `WINIT_UNIX_BACKEND=x11 cargo run`

**Comment by rockisch** [comment]
Seems like that "fixed" the issue, but I'm not sure if it's a winit issue, since I didn't had any issues running conrod using winit.

And will this get fixed sometime, or wayland users will always need to run Azul apps with Xwayland?

Also, I guess it wouldn't hurt to add this to the Getting Starded section of the wiki.

**Comment by rockisch** [comment]
Ah, I can see that this is already being discussed in https://github.com/maps4print/azul/issues/123
