### ISSUE TITLE
macos can not run examples 

### ISSUE THREAD

**Issue by yunfengsay** [maps4print/azul#148]
## Version / OS

* azul version: clone from this git address

* Operating system: MacBook Pro (Retina, 15-inch, Mid 2015)

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

 cargo run --example slider

## Additional Information

![image](https://user-images.githubusercontent.com/15527378/55771578-3371f000-5abb-11e9-8449-24e7da429a3d.png)
An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/zhangyunfeng/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/ed2ad88/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn
core::ops::function::Fn::call
std::panicking::rust_panic_with_hook
std::panicking::begin_panic
glutin::platform::platform::Context::new
glutin::combined::CombinedContext::new
azul::window::create_gl_window
<azul::window::Window<T>>::new
<azul::window::Window<T>>::new_hot_reload
<azul::app::App<T>>::create_hot_reload_window
xml::main
std::rt::lang_start::{{closure}}
std::panicking::try::do_call
std::rt::lang_start_internal
std::rt::lang_start

**Comment by fschutt** [comment]
Closing because this is the same as #131, please see that issue for more information.
