### ISSUE TITLE
white space on the bottom of the window

### ISSUE THREAD

**Issue by JAicewizard** [maps4print/azul#155]
## Description
Using the counter example there is a white bar on the bottom of the space, if I don't use any CSS besides background-color and height:10000px; it does display the button in the white space, but by default it is not used

## Version / OS
(arch)-linux apr 16th 

* azul version: 0.1.0

* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce
Run the example code in the starters guide

**Comment by fschutt** [comment]
Closing in favor of #165 - same bug, but a better report
