### ISSUE TITLE
Crash on hello world

### ISSUE THREAD

**Issue by vipenzo** [maps4print/azul#159]
## Description

Panicked on my first try at using it, was just following the tutorial.
## Version / OS

Ubuntu 18.04.2 LTS
* azul version:
"0.1.0"

* Operating system:
Linux

* Windowing system (X11 or Wayland, Linux only):
X11

## Steps to Reproduce

launch cargo run on this:
extern crate azul;

use azul::prelude::*;

struct MyDataModel { }

impl Layout for MyDataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        Dom::div()
    }
}

fn main() {
    let mut app = App::new(MyDataModel { }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}

## Additional Information

   Compiling my_first_azul_app v0.1.0 (/home/ll250/svncaselle/HWSim/client/rustone/my_first_azul_app)
    Finished dev [unoptimized + debuginfo] target(s) in 11.29s
     Running `target/debug/my_first_azul_app`
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: src/libcore/result.rs at line 997 in thread main

Error information:
called `Result::unwrap()` on an `Err` value: CreateError(OsError("GL context creation failed"))

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:482
std::panicking::continue_panic_fmt @ panicking.rs:385
 @ panicking.rs:312
core::panicking::panic_fmt @ panicking.rs:85
core::result::unwrap_failed @ macros.rs:16
<core::result::Result<T, E>>::unwrap @ result.rs:798
my_first_azul_app::main @ main.rs:14
std::rt::lang_start::{{closure}} @ rt.rs:64
std::rt::lang_start_internal::{{closure}} @ rt.rs:49
std::panicking::try::do_call @ panicking.rs:297
 @ lib.rs:92
std::panicking::try @ panicking.rs:276
std::panic::catch_unwind @ panic.rs:388
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64
unresolved function

sh: 1: Syntax error: Bad function name

**Comment by fschutt** [comment]
This is a problem with your OpenGL driver, you are probably on software rasterization (since it says your driver is called "swrast"). What drivers do you have installed and what GPU are you using? Are you using a virtual machine?

**Comment by vipenzo** [comment]
I was using nvidia drivers and I was not inside a VM. I reinstalled the drivers with the .run script nvidia provides and now azul works fine.

**Comment by fschutt** [comment]
Okay, I'm closing this then as it's less a problem of Azul and more of a problem of a wrong graphics driver installation

**Comment by zephyrzoom** [comment]
I got the same problem. I think the Ubuntu default nvidia driver make the crash.
