### ISSUE TITLE
attempting to run hello_world on OS X Mojave throws the below exception

### ISSUE THREAD

**Issue by jpitz31** [maps4print/azul#164]
## Description

Please provide a detailed description of the behavior you're seeing or the behavior
you'd like to see **below** this comment.
Joes-iMac:azul jpitz$ cargo run --example hello_world
   Compiling azul v0.1.0 (/Users/jpitz/Code/Rust/azul/azul)
    Finished dev [unoptimized + debuginfo] target(s) in 12.30s
     Running `target/debug/examples/hello_world`
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/jpitz/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/380b7e7/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:482
std::panicking::begin_panic @ panicking.rs:412
glutin::platform::platform::Context::new @ mod.rs:61
glutin::combined::CombinedContext::new @ combined.rs:58
azul::window::create_gl_window @ window.rs:845
<azul::window::Window<T>>::new @ window.rs:536
<azul::app::App<T>>::create_window @ app.rs:298
hello_world::main @ hello_world.rs:28
std::rt::lang_start::{{closure}} @ rt.rs:64
std::panicking::try::do_call @ panicking.rs:297
 @ lib.rs:92
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64
<img width="424" alt="Screen Shot 2019-04-25 at 10 41 59 AM" src="https://user-images.githubusercontent.com/1331148/56756515-c743ed00-6746-11e9-9da7-dd8d31c1c009.png">

## Version / OS
OS X Mojave

* azul version:
v0.1.0

* Operating system:
OS X

## Steps to Reproduce
cargo run --example hello-world

## Additional Information

Sorry I could not find a log file in the debug folder
If you need me try anything, please ask

**Comment by fschutt** [comment]
Yes, that's a known bug, already covered in #131.
