### ISSUE TITLE
Support for rendering HTML in a DOM object.

### ISSUE THREAD

**Issue by GanbaruTobi** [maps4print/azul#172]
## Description
For mine and probably other projects it is sometimes interesting to render a webpage as part of a view. Since azul already uses servo i thought it might be possible to translate an HTML file or response into a 'dom' element. Here it should use the existing functionality in servo, not the dom elements of azul.

## Describe your solution
I expect an iframe like thing. A part of a view which displays a webpage. 

## Are there alternatives or drawbacks?
It might be difficult to determine how mouse action are supposed to work on such an element

## Is this a breaking change
No, it should be a feature. Hopefully

## Additional notes
If this is not interesting for the project, I'm still interested in informations on a smart way to implement this feature in azul. I myself am not an experienced programmer, so my code might not be of any value to others. I would still make it public.

**Comment by GanbaruTobi** [comment]
Sorry, by further reviewing and writting tests i figured it is not possible to use azul for my project and i don't want to create more work before basic functionality isn't provided. Maybe this is something for the future.
Excuse me

**Comment by fschutt** [comment]
Technically you could open a web browser window from azul (i.e. on_click -> open transient browser window). Or you could write the UI in JS and use Rust for the backend (using [web-view](https://crates.io/crates/web-view) - see https://github.com/fschutt/woco_carplan for an example app where I did that). web-view uses the native browser engine, i.e. IE on Windows, WebView on Mac, gtk-web on Linux.
