### ISSUE TITLE
An unexpected panic ocurred, the program has to exit - Getting Started

### ISSUE THREAD

**Issue by jaywalker76** [maps4print/azul#181]
## Description

While trying to following the steps in this tutorial:
https://github.com/maps4print/azul/wiki/Getting-Started
got the following error
## Version / OS

* azul version: 
Loaded as dependency in Cargo.toml as:
azul = { git = "https://github.com/maps4print/azul" }

* Operating system: MacOS Mojave 10.14.4

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

Following the steps in the aforementioned tutorial, when running cargo run, I get the following error:
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /---/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/bf2933b/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:478
std::panicking::begin_panic @ panicking.rs:408
glutin::platform::platform::Context::new @ mod.rs:61
glutin::combined::CombinedContext::new @ combined.rs:58
azul::window::create_gl_window @ window.rs:852
azul::window::Window<T>::new @ window.rs:445
azul::app::App<T>::create_window @ app.rs:207
my_first_azul_app::main @ main.rs:15
std::rt::lang_start::{{closure}} @ rt.rs:64
std::panicking::try::do_call @ panicking.rs:293
 @ lib.rs:87
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64

**Comment by fschutt** [comment]
Yes, same bug as in #131, see that issue.
