### ISSUE TITLE
Hello World Crash MacOS

### ISSUE THREAD

**Issue by JoeHowarth** [maps4print/azul#187]
## Description
Crashes on Hello World with below error message on macOS

## Version / OS

* azul version: 6763ca72f711e5874bf9d259a0eea9fe5f32f16c

* Operating system: macOS

## Steps to Reproduce
cargo build
cargo run --example hello_world

## Additional Information
An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/jh/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/bf2933b/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:478
std::panicking::begin_panic @ panicking.rs:408
glutin::platform::platform::Context::new @ mod.rs:61
glutin::combined::CombinedContext::new @ combined.rs:58
azul::window::create_gl_window @ window.rs:890
azul::window::Window<T>::new @ window.rs:483
azul::app::App<T>::create_window @ app.rs:211
hello_world::main @ hello_world.rs:26
std::rt::lang_start::{{closure}} @ rt.rs:64
std::panicking::try::do_call @ panicking.rs:293
 @ lib.rs:87
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64

**Comment by fschutt** [comment]
yes, see #131
