### ISSUE TITLE
"not yet implemented" on macOS 10.14.6

### ISSUE THREAD

**Issue by jeremyDudo** [maps4print/azul#205]
## Version / OS

* azul version:
azul = { git = "https://github.com/maps4print/azul" }
(There is no crate, I don't know how to check version without it)
* Operating system:
macOS 10.14.6

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

I installed azul and CMake onto my computer

My cargo.toml is:
"""
[package]
name = "hello_world"
version = "0.1.0"
authors = ["dudo"]
edition = "2018"

[dependencies]
azul = { git = "https://github.com/maps4print/azul" }
"""
I replicate the following in main.rs:
"""
extern crate azul;

use azul::prelude::*;

struct MyDataModel { }

impl Layout for MyDataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        Dom::div()
    }
}

fn main() {
    let mut app = App::new(MyDataModel { }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
"""

And I receive the following error in the error.log:
"""
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/dudo/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/bf2933b/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:478
std::panicking::begin_panic @ panicking.rs:408
glutin::platform::platform::Context::new @ mod.rs:61
glutin::combined::CombinedContext::new @ combined.rs:58
azul::window::create_gl_window @ window.rs:890
azul::window::Window<T>::new @ window.rs:483
azul::app::App<T>::create_window @ app.rs:211
hello_world::main @ main.rs:15
std::rt::lang_start::{{closure}} @ rt.rs:64
std::panicking::try::do_call @ panicking.rs:293
 @ lib.rs:85
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64
"""

**Comment by fschutt** [comment]
Same issue as #131.
