### ISSUE TITLE
Fontconfig-sys fails to build on Ubuntu

### ISSUE THREAD

**Issue by foxjazz** [maps4print/azul#206]
Windows or ubuntu subsystem
Build fails  (cargo build) on project

  Compiling gl_generator v0.11.0
error: failed to run custom build command for `servo-fontconfig-sys v4.0.7 (https://github.com/maps4print/azul-dependencies?rev=bf2933b9aac43a7003278862772250398e4fa457#bf2933b9)`
process didn't exit successfully: `/mnt/g/rust/azul/target/debug/build/servo-fontconfig-sys-a68a4acab3010bbd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by adrianromero** [comment]
I have the same problem in Debian 9. Here the full ouput of building a simple application if it helps.

[azulbuilderror.log](https://github.com/maps4print/azul/files/3537801/azulbuilderror.log)

**Comment by fschutt** [comment]
Yeah well, it's more of a problem that should be reported to servo-fontconfig-sys, shouldn't it - I can't do much about the bugs of a dependency.

**Comment by adrianromero** [comment]
Oh!, Thanks for the clarification. I will review Fontconfig-sys tracker.

**Comment by lbordowitz** [comment]
For what it's worth, I was able to install it with the following packages. Not sure which are actually necessary, though.

`sudo apt install libfontconfig1-dev fontconfig-config fontconfig vflib3-dev`
`sudo snap install cmake --classic`

**Comment by azah** [comment]
This is because the `master` branch has an old dependency to `servo-fontconfig-sys`.

Checkout the `unvendor_dependencies` branch and build from that, it's more up to date.

**Comment by fschutt** [comment]
I have replaced `fontconfig-sys` with `rust-fontconfig`, which is a pure-Rust rewrite of the relevant fontconfig functions that azul uses (selecting and querying fonts). Since `fontconfig-sys` is not needed anymore for building azul, I am closing this issue. The master branch has been updated.
