### ISSUE TITLE
Dom::div with no children does not produce closing tag

### ISSUE THREAD

**Issue by SuperCuber** [maps4print/azul#208]
## Description
`Dom::div()` without children produces no closing tag.
* azul version: bb5ab4c2596f41e98630404662521200592243bd
* Operating system: Windows 10

## Steps to Reproduce

```rust
println!("{}", Dom::<DataModel>::div().debug_dump());
```
The following code produces the output:
```html
<div>
```
when it is expected to produce:
```html
<div>
</div>
```

This causes buggy rendering in the window if used.

I got this bug when trying to put a newline between the label and button on the hello_world example; is there a better way to do that?

**Comment by fschutt** [comment]
Yes, just use two newlines. I.e.

```
<div>
Hello

Newline

Another line
</div>
```

As for the XML output, it's just a debug dump - I'll look into it, but it's a fairly low priority bug, it's mostly just meant for debugging.

**Comment by SuperCuber** [comment]
@fschutt I can't seem to get it to work, with the following code (modified from hello_world.rs)
```rust
        let dom = Dom::div()
            .with_child(label)
            .with_child(Dom::label("\n\n"))
            .with_child(button);
```
Outputs the following xml:
```html
<div>
    <p class="__azul-native-label">0</p>
    <p>

</p>
    <div class="__azul-native-button" tabindex="0" callbacks="(Hover(MouseUp)=Callback @ 0x7ff7f8c5a3c0)">
        <p>Update counter</p>
    </div>
</div>
```

Output looks like [this](https://owo.whats-th.is/AM6XNAm.png), note label and button on the same line.
The cut-out counter also happens with just the example itself, I figured it was an unrelated bug (and with the status update you did say the layout solver was messed up) so didn't include it in this issue.

**Comment by SuperCuber** [comment]
Looks like this is a leftover
