### ISSUE TITLE
Azul doesn't display background color of window 

### ISSUE THREAD

**Issue by renannprado** [maps4print/azul#210]
## Description

I'm trying to change the background color using the by extending the default `AppConfig`, but it doesn't seem to be respected.

## Output

![image](https://user-images.githubusercontent.com/2359543/63295461-fc171980-c2cc-11e9-8b50-df7ebf0163eb.png)

## Version / OS

* azul version: `bb5ab4c2596f41e98630404662521200592243bd`

* Operating system: 

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

* Windowing system (X11 or Wayland, Linux only): Wayland

## Steps to Reproduce

```rust
extern crate azul;

use azul::prelude::*;

struct MyDataModel {
}

impl Layout for MyDataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        Dom::div()
    }
}

fn main() {
    let app_config = AppConfig { background_color: ColorU { r: 0, g: 100, b: 0, a: 0}, ..AppConfig::default() };

    let mut app = App::new(MyDataModel { }, app_config).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
```

## Additional Information
I'm forcing to run with X11: `WINIT_UNIX_BACKEND=x11 cargo run`

**Comment by fschutt** [comment]
This issue should now be solved on the master branch. WebRender had multiple issues regarding background color rendering, I've fixed it here:

https://github.com/maps4print/azul/blob/564dba9e093ba00282175d311dd74707014362b9/azul-core/src/display_list.rs#L85-L94

Transparency still won't work, but that is a problem with some windowing implementations not respecting RGBA textures.
