### ISSUE TITLE
can we remove title bar ?

### ISSUE THREAD

**Issue by ayonsaha2011** [maps4print/azul#215]
can we remove title bar in azul window like in Electron frameless window -> 

> const { BrowserWindow } = require('electron')
> let win = new BrowserWindow({ width: 800, height: 600, frame: false })
> win.show()

**Comment by fschutt** [comment]
```rust
// use branch unvendor_dependencies
let app = App::new(MyDataModel { }, AppConfig::default());
let window = WindowCreateOptions {
     state: WindowState {
          size: LogicalSize::new(800.0, 600.0),
          decorations: false,
          .. Default::default()
     },
     css,
     .. Default::default()
};

app.run(window);
```

**Comment by ayonsaha2011** [comment]
@fschutt 

`   |
23 |             decorations: false,
   |             ^^^^^^^^^^^ `azul::window::WindowState` does not have this field
   |
   = note: available fields are: `title`, `size`, `position`, `is_maximized`, `is_fullscreen` ... and 10 others`

**Comment by ayonsaha2011** [comment]
okay it's has_decorations like -> 

let mut app = App::new(MyDataModel { }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions{
        state: WindowState {
            has_decorations: false,
            .. Default::default()
        },
        .. Default::default()
    }, css::native()).unwrap();
    app.run(window).unwrap();
