### ISSUE TITLE
Failed to build Hello world

### ISSUE THREAD

**Issue by mdeering24** [maps4print/azul#218]
## Description
I copied the code for the hello world example and it failed to build

## Version / OS
Mac OS

* azul version:
 latest version of Azul

* Operating system:
Mac OS

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce
Copy the code for hello world and run 'cargo run'

Below is the error message I got 
An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/deering/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/bf2933b/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:481
std::panicking::begin_panic @ panicking.rs:411
glutin::platform::platform::Context::new @ mod.rs:61
glutin::combined::CombinedContext::new @ combined.rs:58
azul::window::create_gl_window @ window.rs:890
azul::window::Window<T>::new @ window.rs:483
azul::app::App<T>::create_window @ app.rs:211
my_first_azul_app::main @ main.rs:15
std::rt::lang_start::{{closure}} @ rt.rs:64
std::panicking::try::do_call @ panicking.rs:296
 @ lib.rs:82
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64

**Comment by fschutt** [comment]
1. Use the `unvendor_dependencies` branch, it's fixed there
2. See #131
