### ISSUE TITLE
An unexpected panic ocurred  at winit::platform::platform::wayland::window::Window::get_current_monitor(...)

### ISSUE THREAD

**Issue by ivmazurenko** [maps4print/azul#222]
## Description
An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: src/libcore/option.rs at line 378 in thread main

Error information:
called  on a  value

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
std::panicking::rust_panic_with_hook @ panicking.rs:477
std::panicking::continue_panic_fmt @ panicking.rs:380
 @ panicking.rs:307
core::panicking::panic_fmt @ panicking.rs:84
core::panicking::panic @ panicking.rs:49
core::option::Option<T>::unwrap @ macros.rs:12
winit::platform::platform::wayland::window::Window::get_current_monitor @ window.rs:314
winit::platform::platform::Window::get_current_monitor @ mod.rs:335
winit::window::<impl winit::Window>::get_current_monitor @ window.rs:406
azul::window::get_hidpi_factor @ window.rs:869
azul::window::FakeDisplay::new @ window.rs:803
azul::app::App<T>::new @ app.rs:177
rtests::main @ main.rs:17
std::rt::lang_start::{{closure}} @ rt.rs:64
std::rt::lang_start_internal::{{closure}} @ rt.rs:49
std::panicking::try::do_call @ panicking.rs:292
 @ lib.rs:80
std::panicking::try @ panicking.rs:271
std::panic::catch_unwind @ panic.rs:394
std::rt::lang_start_internal @ rt.rs:48
std::rt::lang_start @ rt.rs:64
unresolved function

* azul version:
0862eb02a46bc6a6610bc6911c3420b5f1a32665

* Operating system:
Fedora 31

* Windowing system (X11 or Wayland, Linux only):
gnome wayland

## Steps to Reproduce
``` toml
[package]
name = "rtests"
version = "0.1.0"
authors = ["1"]
edition = "2018"

[dependencies]
azul = {git = "https://github.com/maps4print/azul" }
```

``` rust
use azul::{prelude::*, widgets::label::Label};

struct DataModel {}

impl Layout for DataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        let label = Label::new("some text").dom();

        Dom::new(NodeType::Div).with_child(label)
    }
}

fn main() {
    let mut app = App::new(DataModel {}, AppConfig::default()).unwrap();
    let window = app
        .create_window(WindowCreateOptions::default(), css::native())
        .unwrap();
    app.run(window).unwrap();
}
```

**Comment by fschutt** [comment]
Moved to #190
