### ISSUE TITLE
Blank window in Win10 (Updated with some debug info)

### ISSUE THREAD

**Issue by foxboxpdx** [maps4print/azul#223]
## Description

Programs using Azul compile and run, but even when testing the examples (counter, etc), only a blank window appears.

## Version / OS

* azul version: Azul 0.1.0 #5984b802

* Rust/Cargo 1.38.0 (same behavior previous version)

* Operating system: Windows 10 Pro build 18362

## Steps to Reproduce

- Copy example code
- cargo build/cargo run

## Additional Information

Screenshot attached.  

![azul](https://user-images.githubusercontent.com/13994606/66278379-4a707f80-e85d-11e9-9669-3a6c723945d6.PNG)

**Comment by foxboxpdx** [comment]
Some additional information now that I've had a chance to go back and poke at this again.

For the sake of debugging, I added println! statements in each step of the application process: calling App::new, calling app.create_window, calling app.run, within MyApp::new, in the example button callback function, and when executing MyApp.layout.

I can see on startup that MyApp.layout is executed 4 times while the window is initializing, and if no input is provided, obviously nothing else happens.

Any time the mouse enters, leaves, or clicks on the blank Azul window, I see MyApp.layout is being executed again.  Random clicking around to try to find the example button object to see if I could trigger the callback function didn't seem to work; if the button "exists" in the emptiness, I couldn't find it.

Finally, just for the sake of trying, I put a println! into MyApp.layout that would spit out the Dom<Self> before returning it so I could see what was inside.  Don't know if this will be of any help but here's what that struct looked like:

`Dom { arena: Arena { node_layout: NodeHierarchy { internal: [Node { parent: None, previous_sibling: None, next_sibling: None, first_child: Some(NodeId(1)), last_child: Some(NodeId(2)) }, Node { parent: Some(NodeId(0)), previous_sibling: None, next_sibling: Some(NodeId(2)), first_child: None, last_child: None }, Node { parent: Some(NodeId(0)), previous_sibling: Some(NodeId(1)), next_sibling: None, first_child: Some(NodeId(3)), last_child: Some(NodeId(3)) }, Node { parent: Some(NodeId(2)), previous_sibling: None, next_sibling: None, first_child: None, last_child: None }] }, node_data: NodeDataContainer { internal: [NodeData {         node_type: NodeType::Div,       ids: [],        classes: [],    callbacks: [],
default_callback_ids: [],       dynamic_css_overrides: [],      is_draggable: false,    tab_index: None, }, NodeData {
node_type: NodeType::Label { Static("Test") },  ids: [],        classes: [Static("__azul-native-label")],       callbacks: [],  default_callback_ids: [],       dynamic_css_overrides: [],      is_draggable: false,    tab_index: None, }, NodeData {  node_type: NodeType::Div,       ids: [],        classes: [Static("__azul-native-button")],      callbacks: [(Hover(MouseUp), Callback @ 0x7ff7e72925f0)],       default_callback_ids: [],       dynamic_css_overrides: [],      is_draggable: false,    tab_index: Some(Auto), }, NodeData {    node_type: NodeType::Label { Static("HONK HONK") },     ids: [],        classes: [],    callbacks: [],  default_callback_ids: [],       dynamic_css_overrides: [],      is_draggable: false,    tab_index: None, }] } }, root: NodeId(0), head: NodeId(0) }`

If there's any other debug info I can provide please let me know.

**Comment by fschutt** [comment]
Yeah well, the layout solver is all kinds of broken right now. I'm working on replacing it with a "proper" layout solver, but that's a pretty big task overall. I am working on it on the `/unvendor_dependencies` branch, but there are still problems with redrawing and updating the screen. Thanks for reporting anyways.

**Comment by foxboxpdx** [comment]
No worries, thanks for the update.

**Comment by fenhl** [comment]
From the screenshot it looks like the Windows UI scale is above 100%, so this is probably a duplicate of #174.

**Comment by foxboxpdx** [comment]
I think you're right, I'll close.

I'll test using the unvendor_dependencies branch when I can and will comment in #174 if I get any new information.
