### ISSUE TITLE
Application crashes immediately at launch

### ISSUE THREAD

**Issue by CoNsTaRs** [maps4print/azul#229]
## Description
Hello World example

## Version / OS

* azul version:
from github

* Operating system:
Mac OS 10

* Windowing system (X11 or Wayland, Linux only):

## Additional Information
`An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/constarwu/.cargo/git/checkouts/azul-dependencies-70bb1f94316762f9/bf2933b/tomaka.glutin#23b3b10/src/platform/macos/mod.rs at line 61 in thread main

Error information:
not yet implemented

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn
std::panicking::rust_panic_with_hook
std::panicking::begin_panic
glutin::combined::CombinedContext::new
azul::window::create_gl_window
azul_test::main
std::rt::lang_start::{{closure}}
std::rt::lang_start_internal`

in line 61 `Context::new`:

`if gl_attr.sharing.is_some() {
    unimplemented!()
 }`

**Comment by fschutt** [comment]
Same issue as the pinned #131.
