### ISSUE TITLE
Linking with link.exe failed using azul.

### ISSUE THREAD

**Issue by denik7770** [maps4print/azul#239]
I am always getting this error on compiling my app.. Everytime I get an error: 

>    Compiling my_first_azul_app v0.1.0 (C:\Users\brooooooo\my_first_azul_app)
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.12h271belijds2vk.rcgu.o" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.195dlj3cuhn5nv93.rcgu.o" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.1ps9eo493ohl016k.rcgu.o" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.2fd1pl2d0ymbz1kp.rcgu.o" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.3wgv2ymza1axsol8.rcgu.o" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.zuh64t621oqsntk.rcgu.o" "/OUT:C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.exe" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\my_first_azul_app.sxrauna01ep7oh4.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps" "/LIBPATH:C:/msys64/mingw64/lib" "/LIBPATH:C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\build\\tinyfiledialogs-5d178be6dc335a88\\out" "/LIBPATH:C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul-10beb51e60a6f7b1.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_widgets-56398731e929696c.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_layout-289c2c1c95e3f646.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_core-9135ded1b002e9e6.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_native_style-ceac8805a11b75d1.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_css_parser-946d03664b05725c.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_simplecss-f1e3722091a041e5.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_css-9b775070e4dc1a9b.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libazul_dependencies-59aa3a6c6d2f3f39.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libbacktrace-b00f424a17fd2fc4.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\librustc_demangle-297e7dff4b422421.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libfern-24dea57282947307.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libharfbuzz_sys-950b3dff66d65db0.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libxmlparser-cfbb6f0f1dcc539d.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libfont_loader-540b3af2aa38bcae.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libclipboard2-34c64315b14071ea.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libclipboard_win-3b2c605bdb6a8809.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libtinyfiledialogs-61f8c931663e9d29.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libunicode_normalization-7be3ced41c96b5f8.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\librusttype-ab9efc6da050f3e0.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libstb_truetype-6d14e6937b24bd9c.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libordered_float-3fd573f7ab1d60b8.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libapprox-ce0fffc5c6cb3417.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libwebrender-51a76797870c51e4.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libwebrender_api-ebd17d264cb0ce36.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libserde_bytes-c066f682e21a89fb.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libtime-3b00a5ce7b0b8655.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\librayon-0b850a9564bcdeac.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libeither-456b84fc358439e9.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\librayon_core-7e8ad5f240b72e8e.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libnum_cpus-7d39e80597d1d49a.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libcrossbeam_deque-8062e0559a7ae80c.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libcrossbeam_epoch-078304863e919900.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libscopeguard-a72b9c364d40d8c8.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libmemoffset-f217c7c63a0f4b9f.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libcrossbeam_utils-e64690afc8f71888.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libarrayvec-e13c9f7516193410.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libnodrop-8abdad58a9ba3915.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libplane_split-257cbf689cd8438b.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libbinary_space_partition-f4757b8edf197846.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libgleam-8ed2aaba17cab016.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libfxhash-87bbdaa0c077905d.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libbincode-a667e1d9a573351f.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libbyteorder-61add9808ce08c69.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libapp_units-9569bf7631f64518.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libdwrote-3199e21121afd1cc.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libthread_profiler-892a86c4695af108.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libbitflags-35f4a44ccb20f38d.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libeuclid-bb04ab357ea2361b.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libnum_traits-e1eedf59c23aff21.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libserde-477256c99b6818f7.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libglium-5f0068c88371b2b0.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libglutin-e9a2ae96cc7e0b06.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libwinit-f1d7645c3914d5de.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\liblog-73188dff2457620b.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libcfg_if-369e57fbdc333551.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\liblibloading-11c5d9353d34a7a6.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\liblibc-9be01756d2a7466c.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libwinapi-3ebf566b037ddff0.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libfnv-8ec522688d0c0aed.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libsmallvec-a4b68a3e76fac24c.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libunreachable-bfe254f0d1bc3260.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\libvoid-586bc11f0260d1ff.rlib" "C:\\Users\\brooooooo\\my_first_azul_app\\target\\debug\\deps\\liblazy_static-c43afd0b96dbf735.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-a2af7cbca70405c4.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-8f8ad41ed0b34354.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libhashbrown-3442ca764a847dfc.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-726244614f5a8f3a.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libbacktrace-29b7599014a92286.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-519f7f7caa7ec7f2.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-feba7334127a8724.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcfg_if-6d75d87de5ddb74c.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-7dc5efd24952e919.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-b95120d391119ce4.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-0e624f0b43962fb3.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-58985b8c03f907a8.rlib" "C:\\Users\\brooooooo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-27c1b248396c205c.rlib" "harfbuzz.lib" "user32.lib" "comdlg32.lib" "ole32.lib" "opengl32.lib" "advapi32.lib" "comctl32.lib" "d2d1.lib" "dbghelp.lib" "dwmapi.lib" "dwrite.lib" "dxgi.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ole32.lib" "opengl32.lib" "setupapi.lib" "shcore.lib" "shell32.lib" "shlwapi.lib" "user32.lib" "uxtheme.lib" "windowscodecs.lib" "winspool.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'harfbuzz.lib'

error: aborting due to previous error

error: could not compile `my_first_azul_app`.

I looked at many forums, but i did not found an answer..

**Comment by fschutt** [comment]
Seems something specific to the MSVC linker not finding harfbuzz. Harfbuzz is statically linked (it's included as a depedency [`harfbuzz-sys`](https://crates.io/crates/harfbuzz-sys)). Are you able to build https://github.com/servo/rust-harfbuzz or do you get the same error?

I'm sorry, but I currently have no idea how to fix it. Could be something wrong with your VS installation, a caching mistake (try `cargo clean` and build again?) or maybe just install gcc and use the gcc linker? Thanks for reporting anyways.

**Comment by denik7770** [comment]
yup, now I have this problem with hardbuzz(Ive reinstalled Visual Studio)..

**Comment by denik7770** [comment]
Ive fixed it. Before, i was making rust apps with Jetbrains Clion. A new project of clion and a new project make with cargo were different a bit, so when I made a simple cargo app, everything worked

**Comment by liusong1111** [comment]
I met it and resolved by installing harfbuzz:

```
vcpkg install harfbuzz --triplet=x64-windows
```

But after compiling succeed, #235 comes . 

It's promissing, especially comparing with electron.

good job!

**Comment by fschutt** [comment]
Harfbuzz is now not required anymore for building. I have switched to [allsorts](https://yeslogic.com/blog/allsorts-rust-font-shaping-engine/), which is a pure-Rust replacement for Harfbuzz. So I am closing this issue as it's not relevant anymore.
