### ISSUE TITLE
Can't compile on windows

### ISSUE THREAD

**Issue by LovaTahina** [maps4print/azul#249]
## Description
I have a problem at compiling. I followed the tutorial and compilation stopped. Here is the compilation message:
error: failed to run custom build command for `servo-freetype-sys v4.0.5`

Caused by:
  process didn't exit successfully: `C:\Users\lrandrianaris\Documents\Innovation\smarttrade\local\win\target\debug\build\servo-freetype-sys-0239bf3a1f02384c\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\lrandrianaris\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\servo-freetype-sys-4.0.5\\freetype2" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DWITH_BZip2=OFF" "-DWITH_HarfBuzz=OFF" "-DWITH_PNG=OFF" "-DWITH_ZLIB=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\lrandrianaris\\Documents\\Innovation\\smarttrade\\local\\win\\target\\debug\\build\\servo-freetype-sys-2ad1d597bd644450\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
thread 'main' panicked at '
failed to execute command: Le fichier spécifié est introuvable. (os error 2)
is `cmake` not installed?

build script failed, must exit now', C:\Users\lrandrianaris\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:885:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

## Version / OS
windows10

* azul version:
last stable version

* Operating system:
Windows

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce
after setting dependencies as azul = { git = "https://github.com/maps4print/azul" }
and editing main.rs with sample code 

cargo build

**Comment by fschutt** [comment]
> failed to execute command: Le fichier spécifié est introuvable. (os error 2)
> is cmake not installed?

See the [instructions in the installation section on Windows](https://github.com/maps4print/azul/wiki/Installation#system-dependencies) - you need to install `cmake`: https://cmake.org/ - it's necessary to build the HarfBuzz and FreeType C libraries.

**Comment by LovaTahina** [comment]
Thanks, compilation running
