### ISSUE TITLE
Where can I set up texts and other resources before I load a window?

### ISSUE THREAD

**Issue by OptimisticPeach** [maps4print/azul#26]
Hi there, I'm trying to load texts into the window before the layout() function is called, and then pass the `TextId`s to it internally, where can I initially load these texts, I can't find any kind of setup function where I can use an `AppState<T>`, unless I use a button, but I can't force users to have to push a button for text to appear. Thanks!

**Comment by fschutt** [comment]
The `App` struct itself should have the necessary methods - `add_text_cached` and `add_font`. This can be done before the `app.run()` function is called (i.e. when the program starts). You can use `add_text_cached` and `add_font` to get a `TextId`. I.e.:

```rust
let font_data = include_bytes!("Roboto.ttf");
let font_id = FontId::External("Roboto".into());

let mut app = App::new(MyDataModel { text: None }, AppConfig::default());
app.add_font(font_data, font_id.clone());
// Calculates and caches the text layout - need to provide the font, 
// the font size and your text (+ optional letter spacing)
app.add_text_cached("My very long text", font_id, FontSize::px(10.0), None);
// Now run (calls the layout() function for the first time)
app.run(Window::new(WindowCreateOptions::default()).unwrap()).unwrap();
```

Be sure to delete the font at some point, it doesn't delete itself (except when the run() function ends). Hope that answers your question.

**Comment by fschutt** [comment]
Well, you don't have to specify it, as it will fall back to the default `sans-serif` font. Plus, the default fonts (`sans-serif`, `serif`, `cursive`, etc.) are always loaded. You can of course do this:

```rust
let font_id = FontId::Builtin("sans-serif".into());

let mut app = App::new(MyDataModel { text: None }, AppConfig::default());
let text_id = app.add_text_cached("My very long text", font_id, FontSize::px(10.0), None);
app.app_state.data.modify(|state| state.text = Some(text_id));
app.run(Window::new(WindowCreateOptions::default()).unwrap()).unwrap();
```

If you don't specify a size, it will fallback to the default font size, which is 10px. If you don't specify a font in the CSS, it will fall back to the default font, which is `sans-serif`. If you want to use a custom font for everything, put `* { font-family: "Roboto" }` somewhere in your CSS.

**Comment by OptimisticPeach** [comment]
Ah, okay, so if i understand correctly:
- A `FontId` refers to a cached version of text with a certain font and size,
- If I set it as a different font (Or size) to that in the `FontId`, then it is recalculated on the fly,
- If I don't specify it in either place, then I end up with the default font
- And, if I only specify it on the rust end, then I get the font and size specified in the cached Text referred to by the `FontId`

**Comment by fschutt** [comment]
Yes, but I think you meant a `TextId`, not a `FontId` - yes, a `TextId` corresponds to a cached version of the text with font + size (essentially the cached glyph positions on the page - if the font would be scaled, the glyph positions need to be recalculated). A `FontId` is just a string that corresponds to a parsed-and-loaded font file (usually .ttf or .otf).

To (4) - yes, unless the font was removed (via `delete_font`) in the meantime - i.e. in the time where the `TextId` was created and the `layout()` function was called, then it will (I think) either fall back to the default font or just not render the text.

Right now the support for automatically adding / removing / loading / unloading fonts is a bit flaky. On webpages you can just load and unload fonts and images and the JS garbage collector takes care of deleting them, but here you have to watch out that you don't accidentally add fonts and never remove them. This is a bit tricky and I hope to improve that API in the future.

**Comment by OptimisticPeach** [comment]
Yes, I did mean TextId, thanks! This is very important for the document loader I'm writing.

**Comment by OptimisticPeach** [comment]
Hello again, how would one set the color of the text? I have tried setting the color property in the css to no avail. I'm getting no text output, so I wanted to be sure that I can see the text before I delve into debugging.

**Comment by OptimisticPeach** [comment]
Ah, my bad, it was the `color` property.
