### ISSUE TITLE
If would like to split out text shaping what is the plan?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [maps4print/azul#264]
text shaping is good in its own, i would like it depend only on foundations. what would be plan to move it out of azul, but still usable by azul and by me?

**Comment by fschutt** [comment]
already done that: https://docs.rs/azul-text-layout/0.0.4/azul_text_layout/

**Comment by dzmitry-lahoda** [comment]
it depends on https://docs.rs/azul-core/0.0.2/azul_core/callbacks/index.html which is the purpose for GUI, not for rendering e.g. into PDF or image.

**Comment by fschutt** [comment]
yeah, I can't split that out, sorry. azul-core does not have dependencies (all deps are optional), so it's fine. Just use `azul-core = { version = "0.2.0", default-features = false }` and you won't have a dependency problem.
