### ISSUE TITLE
couldn't read D:\soft\cargo/lib/azul-dll-0.0.1/target/release/azul.dll

### ISSUE THREAD

**Issue by adminSxs** [maps4print/azul#266]
OS: winsows10
rust version:   nightly-x86_64-pc-windows-msvc
azul version:  azul={git="https://github.com/maps4print/azul.git",branch="new_old_layout"}

execute command: cargo build
```shell
error: couldn't read D:\soft\cargo/lib/azul-dll-0.0.1/target/release/azul.dll: 系统找不到指定的路径。 (os error 3)
    --> D:\soft\cargo\git\checkouts\azul-f3b1e21a5e685cad\8375633\azul\src/rust\dll.rs:7273:30
     |
7273 | ...[u8] = include_bytes!(concat!(env!("CARGO_HOME"), "/lib/", "azul-dll-", env!("CARGO_PKG_VERSION"), "/target/release/azul.dll")); /* !!...
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)


```

**Comment by fschutt** [comment]
`cd azul-dll && cargo install --path .`

`azul-dll` has to be built before `azul` can be built, azul is distributed as a DLL to provide compatibility with C and C++. `azul` tries to find the `D:\soft\cargo/lib/azul-dll-0.0.1/target/release/azul.dll` because that's where `azul-dll` [installs itself](https://github.com/maps4print/azul/blob/83756336f3922bd9f59cf61eea42f93f263a8932/azul-dll/build.rs#L66).

**Comment by adminSxs** [comment]
> `cd azul-dll && cargo install --path .`
> 
> `azul-dll` has to be built before `azul` can be built, azul is distributed as a DLL to provide compatibility with C and C++. `azul` tries to find the `D:\soft\cargo/lib/azul-dll-0.0.1/target/release/azul.dll` because that's where `azul-dll` [installs itself](https://github.com/maps4print/azul/blob/83756336f3922bd9f59cf61eea42f93f263a8932/azul-dll/build.rs#L66).

``cargo install --path .`` only execute exe file .not dll file

**Comment by adminSxs** [comment]
> `cd azul-dll && cargo install --path .`
> 
> `azul-dll` has to be built before `azul` can be built, azul is distributed as a DLL to provide compatibility with C and C++. `azul` tries to find the `D:\soft\cargo/lib/azul-dll-0.0.1/target/release/azul.dll` because that's where `azul-dll` [installs itself](https://github.com/maps4print/azul/blob/83756336f3922bd9f59cf61eea42f93f263a8932/azul-dll/build.rs#L66).

cargo install --path . only generate exe file .not dll file

**Comment by fschutt** [comment]
Run the `./test.bat` file, at least that should work. Sometimes the azul-dll install script works, sometimes it doesn't and I don't know why. When azul is released, the repository will provide pre-built DLL files, so that these issues don't happen anymore.

azul is very WIP right now, you might want to wait for a proper release. I'm currently working on the layout, I hope it'll be done this week.

**Comment by adminSxs** [comment]
> Run the `./test.bat` file, at least that should work. Sometimes the azul-dll install script works, sometimes it doesn't and I don't know why. When azul is released, the repository will provide pre-built DLL files, so that these issues don't happen anymore.
> 
> azul is very WIP right now, you might want to wait for a proper release. I'm currently working on the layout, I hope it'll be done this week.

is ok, thanks

**Comment by adminSxs** [comment]
> Run the `./test.bat` file, at least that should work. Sometimes the azul-dll install script works, sometimes it doesn't and I don't know why. When azul is released, the repository will provide pre-built DLL files, so that these issues don't happen anymore.
> 
> azul is very WIP right now, you might want to wait for a proper release. I'm currently working on the layout, I hope it'll be done this week.

all exmaples,  cann't run

**Comment by adminSxs** [comment]
> Run the `./test.bat` file, at least that should work. Sometimes the azul-dll install script works, sometimes it doesn't and I don't know why. When azul is released, the repository will provide pre-built DLL files, so that these issues don't happen anymore.
> 
> azul is very WIP right now, you might want to wait for a proper release. I'm currently working on the layout, I hope it'll be done this week.

i use ide is clion

**Comment by fschutt** [comment]
The only examples that work right now are the `public` and `table` examples. If you encounter compilation errors with those examples please post the output.

**Comment by adminSxs** [comment]
> The only examples that work right now are the `public` and `table` examples. If you encounter compilation errors with those examples please post the output.

yes, ```public``` and ```table``` can work

**Comment by fschutt** [comment]
Ok, this issue seems to be solved. For completeness sake, I've replaced the complicated error with a simpler `env!("AZUL_LINK_PATH")`, so that the linker path is not hard-coded to a specific directory.
