### ISSUE TITLE
Cannot compile Azul on M1 MacBook Pro due to older WInit dependency

### ISSUE THREAD

**Issue by andresmakesgames** [maps4print/azul#267]
## Description
Seeing the issue described here: https://github.com/rust-windowing/winit/issues/1782 when trying to run Cargo Update on an M1 MacBook Pro.
Which, as noted as the solution, is solved by using the latest Master version of winit.

## Version / OS
Mac OS Big Sur 11.0.1 (M1 Macbook Pro)

* azul version:
Master

* Operating system:
Mac OS

## Steps to Reproduce
1) Create a project with the dependency azul = { git = "https://github.com/maps4print/azul" }
2) Run Cargo Update
3) Error message will trigger.

**Comment by fschutt** [comment]
This should be solved now on the master branch, please reopen if the issue persists.
