### ISSUE TITLE
Running the HelloWorld application on windows panics

### ISSUE THREAD

**Issue by fbstj** [maps4print/azul#33]
## Description

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target\debug\guitests.exe`
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: libcore\result.rs at line 945 in thread main

Error information:
called `Result::unwrap()` on an `Err` value: CreateError(NotSupported("required extension \"WGL_ARB_create_context_profile\" not found"))

Backtrace:

backtrace::backtrace @ mod.rs:42
backtrace::capture::Backtrace @ capture.rs:88
backtrace::capture::Backtrace @ capture.rs:64
azul::logging::set_up_panic_hooks @ logging.rs:87
core::ops::function::Fn::call<fn(core::panic::PanicInfo*),(core::panic @ function.rs:73
std::panicking @ panicking.rs:482
std::panicking @ panicking.rs:390
std::panicking @ panicking.rs:325
core::panicking @ panicking.rs:77
core::result::unwrap_failed<azul::window @ macros.rs:26
core::result::Result<azul::window::Window<guitests::DataModel>, azul::window::WindowCreateError>::unwrap<azul::window::Window<guitests::DataModel>,azul::window @ result.rs:782
guitests @ main.rs:28
std::rt::lang_start @ rt.rs:74
std::panicking::try @ panicking.rs:310
panic_unwind @ lib.rs:105
std::rt @ rt.rs:58
std::rt @ rt.rs:74
 @ exe_common.inl:253

error: process didn't exit successfully: `target\debug\guitests.exe` (exit code: 101)
```

## Version / OS
* azul version: master
* Operating system: Windows 8

**Comment by fschutt** [comment]
"WGL_ARB_create_context_profile not supported" - what GPU / graphics driver do you have? Seems to be related to https://github.com/tomaka/glutin/issues/637 - if you'd want to run the app, try to comment out this line:

https://github.com/maps4print/azul/blob/ab487b07b687322a4bda6897002a20f136ceba53/src/window.rs#L648

... and see if it runs. Technically it isn't necessary to pin OpenGL to an exact version, `GlRequest::Latest` would suffice. However, I would like to have OpenGL 3.2 core instead of running OpenGL in compatibility mode, not sure if webrender will still run if this restriction is lifted.

**Comment by Yatekii** [comment]
Yeah, I think it's ok to require at least a halfway recent OGL feature set. But I think it should issue a proper error message instead of panicking.

**Comment by fschutt** [comment]
No, don't close this, it'd be a good test case... in the end I would like to distribute azul apps to as many users as possible, even some with low-end graphics. So it's rather important for the framework to adjust to the user rather than the other way around. I'd keep this open.

**Comment by fbstj** [comment]
if I comment out that specific line I then get this panic trying the same code copied to `examples/hello-world.rs` and run as `cargo run --example hello-world`

```
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: libcore\result.rs at line 945 in thread main

Error information:
called `Result::unwrap()` on an `Err` value: CreateError(OsError("wglCreateContextAttribsARB failed: OS Error -1073274731 (FormatMessageW() returned error 317) (os error -1073274731)"))

Backtrace:

backtrace::backtrace @ mod.rs:42
backtrace::capture::Backtrace @ capture.rs:88
backtrace::capture::Backtrace @ capture.rs:64
azul::logging::set_up_panic_hooks @ logging.rs:87
core::ops::function::Fn::call<fn(core::panic::PanicInfo*),(core::panic @ function.rs:73
std::panicking @ panicking.rs:482
std::panicking @ panicking.rs:390
std::panicking @ panicking.rs:325
core::panicking @ panicking.rs:77
core::result::unwrap_failed<azul::window @ macros.rs:26
core::result::Result<azul::window::Window<hello_world::DataModel>, azul::window::WindowCreateError>::unwrap<azul::window::Window<hello_world::DataModel>,azul::window @ result.rs:782
hello_world @ hello-world.rs:28
std::rt::lang_start @ rt.rs:74
std::panicking::try @ panicking.rs:310
panic_unwind @ lib.rs:105
std::rt @ rt.rs:58
std::rt @ rt.rs:74
 @ exe_common.inl:253

error: process didn't exit successfully: `target\debug\examples\hello-world.exe` (exit code: 101)
```

**Comment by fschutt** [comment]
Try commenting out the previous lines, too: 

https://github.com/maps4print/azul/blob/ab487b07b687322a4bda6897002a20f136ceba53/src/window.rs#L644-L647

Does that help? Then it should technically try to use the lates OpenGL version available and with a bit of luck webrender won't notice that you have a version of OpenGL that is too old.

**Comment by fbstj** [comment]
Yes that does successfully run that app, and also the calculator example! thanks for your help!

It does output ```glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues```

**Comment by fschutt** [comment]
If it draws the application correctly, then you can probably ignore the error. I'll remove that code then, to make it work for older drivers.

However, can you run the `debug` example and load the tiger? It loads a custom shader, I'm not sure if that will work or crash.

**Comment by fbstj** [comment]
loading either of the SVGs with that app stops at the following window:

![image](https://user-images.githubusercontent.com/19763/47728040-75b61c00-dc55-11e8-87d7-9d159cd1b17b.png)

**Comment by fschutt** [comment]
Try pulling master again, see if the SVG widget still doesn't work - I adjusted the minimum required OpenGL version for the shader to be OpenGL 1.5 - maybe now it'll load. If not, then it's still better than crashing on startup.

**Comment by Yatekii** [comment]
> If not, then it's still better than crashing on startup.

I have to disagree. I think crashing is a better option than just pretending everything went well =)

**Comment by fbstj** [comment]
they still both show the empty box

**Comment by fschutt** [comment]
... but the calculator works now, doesn't it? It's just the SVG / debug demo that isn't rendering and shows an empty window, yes?

**Comment by fbstj** [comment]
the calculator worked without those lines yes
