### ISSUE TITLE
Docs tutorial example does not compile.

### ISSUE THREAD

**Issue by Niedzwiedzw** [maps4print/azul#38]
## Description
I'm going through the tutorial and this import throws `unresolved reference error`.
```rust
use azul::widgets::*;
```
This fixes the problem and allows to continue through the docs.
```rust
use azul::widgets::button::Button;
use azul::widgets::label::Label;
```

## Version / OS
Ubuntu 18.10
`rustc 1.31.0-nightly (1cf82fd9c 2018-10-30)`

* azul version:
azul = { git = "https://github.com/maps4print/azul" }

* Operating system:
Ubuntu

* Windowing system (X11 or Wayland, Linux only):
i3

**Comment by fschutt** [comment]
Yep, should be fixed now. I'm sorry, it's just that it can happen that non-Rust docs fall behind master. The correct import is:

```rust
use azul::prelude::{*, widgets::{label::Label, button::Button}};
```

**Comment by Ace4896** [comment]
I wasn't able to compile the example with

```rust
use azul::prelude::{*, widgets::{label::Label, button::Button}};
```

I had to use this instead since widgets weren't under prelude:

```rust
use azul::{prelude::*, widgets::{label::Label, button::Button}};
```

**Comment by fschutt** [comment]
Yep, should be fixed now.
