### ISSUE TITLE
Material Design components 

### ISSUE THREAD

**Issue by gedw99** [maps4print/azul#45]
This is a really nice framework for GUI.
Since the cc imports can be made as crates it would be amazing if some standard GUI components were made.
The obvious one is Material Design.

If the community and maintenance are in favour of this I could start on some.

I think it will be much easier to build than the ones in flutter. I would use those as the initial reference in terms of design and behaviour.

Please shout if you have any opinions about this idea.

**Comment by fschutt** [comment]
I'm closing this for now, since it's very easy to develop this in an external crate - now that the new CSS cascading system has landed, this should be fairly doable in an external crate. Feel free to reopen if you have more questions.
