### ISSUE TITLE
On windows, examples are build without console support to display printouts

### ISSUE THREAD

**Issue by DemonOne** [maps4print/azul#46]
On windows, examples (calculator, table, etc...) link against the windowing subsystem (using the linker flag #![windows_subsystem = "windows"]), this means the console isn't available when running the executable using explorer or cmd.exe

This prevents debug prints from being seen by the user, e.g. the table example (in its current limited form) seems not to respond to mouse clicks because those trigger console printouts.

(For some reason using a terminal emulator like msys/mingw makes the console available regardless.)

## Expected Behavior
The console should print "table was clicked" for every mouse click

## Actual Behavior
Nothing is printed

**Comment by ErichDonGubler** [comment]
Maybe linking with support for the console could happen in debug but not release?
