### ISSUE TITLE
Impossible to override native styles using alternate dom syntax

### ISSUE THREAD

**Issue by antonok-edm** [maps4print/azul#53]
## Description

When using `Label::new(...).dom().with_class("foo")`, the `foo` class does not override the native styles provided by `Css::hot_reload_override_native`. Switching to `Dom::new(NodeType::Label(...)).with_class("foo")` works as expected.

## Version / OS

* azul version: latest from git (`679af60`)

* Operating system: Linux

* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce

Starting from the "Hello world" counter example from the README:
Add `.with_class("label")` to the end of the `let label = ` line.
Switch the CSS from `Css::native()` to `Css::hot_reload("style.css").unwrap()`
Add the "style.css" file with the following contents:
```css
.label {
    background-color: #000;
}
```

## Expected Behavior
The top half of the screen should have a black background. This would match the behavior of declaring the label with the following line:
```rust
let label = Dom::new(NodeType::Label(format!("{}", self.counter))).with_class("label");
```

### Actual Behavior
The top half of the screen has a white background.

**Comment by fschutt** [comment]
Yes, this is due to the fact that the CSS cascading system more or less doesn't work at all. I.e. it would only work if you put all class names in it, i.e.:

```css
.__azul-native-label .label {
    background-color: #000;
}
```

This is of course stupid, but I need to rewrite the CSS cascading logic as it's a total mess right now.
