### ISSUE TITLE
Labels on div with position: absolute are behind the div

### ISSUE THREAD

**Issue by CryZe** [maps4print/azul#54]
## Description
If you have a div with position: absolute, you can't place any labels on it without them appearing behind the div.

## Version / OS

* azul version:
Commit: 95dc3539e9882775a35f1d655b0a2c50e85d6569

* Operating system:
Windows

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce
1. Create a div.
2. Add `position: absolute;`
3. Set a background `background-color: black;`
4. Place a label inside.
5. ???
6. Profit

## Expected Behavior
The label gets rendered.

## Actual Behavior
The label gets rendered behind and the depth test rejects it.

## Additional Information
Without a background color:
![https://i.imgur.com/auhmzKF.png](https://i.imgur.com/auhmzKF.png)

With a background color:
![https://i.imgur.com/WN4P9L8.png](https://i.imgur.com/WN4P9L8.png)

**Comment by fschutt** [comment]
Yes, I need to fix this very soon, because it's preventing me from finishing my node graph (where the content of a node appears behind its container) - it has to do with the z-indexing. As far as I know there is no workaround yet.

**Comment by fschutt** [comment]
This should be partially fixed in https://github.com/maps4print/azul/commit/8586f0f84f81dd25368d98954d8a08e1ddb08dd1 - but the z-indexing of box-shadows is still a bit weird, so this problem is probably not completely solved yet.

**Comment by fschutt** [comment]
This was fixed by grouping the elements together (i.e. each `position:absolute` item starts a new group). This is fixed on the lastest master branch (currently https://github.com/maps4print/azul/commit/c79e29f4d57f15b1060eb022f12ad0fa2e971b4e).

**Comment by CryZe** [comment]
Damn, thank you so much. I guess I'll try to experiment with using azul again some time soon. 👍
