### ISSUE TITLE
Fonts are squished

### ISSUE THREAD

**Issue by CryZe** [maps4print/azul#55]
## Description
The text rendering places glyphs very close to each other, much closer than they should be. This is independent of the font and also seems to happen in the screenshots in this repo.

## Version / OS
* azul version: Commit 95dc353
* Operating system: Windows 10

## Steps to Reproduce
Just render any text.

## Expected Behavior
The text shouldn't be squished.
Browser:
![https://i.imgur.com/MSuvYGD.png](https://i.imgur.com/MSuvYGD.png)

## Actual Behavior
The text is squished.
Azul:
![https://i.imgur.com/ipgnnc7.png](https://i.imgur.com/ipgnnc7.png)

**Comment by fschutt** [comment]
Azul uses HarfBuzz and FreeType now instead of rusttype, so this should be fixed now.
