### ISSUE TITLE
Question about sleep times

### ISSUE THREAD

**Issue by whmountains** [maps4print/azul#6]
Somehow I'm failing to understand how this code will wait until 16 ms have passed.

```rust
// Wait until 16ms have passed
let time_end = Instant::now();
let diff = time_end - time_start;
if diff < Duration::from_millis(16) {
    thread::sleep(diff);
}
```

Context here: https://github.com/maps4print/azul/blob/master/src/app.rs#L247-L252

Assume the last frame took 1ms to draw.  `diff == 1` in that case, so the thread will be sleeping for 1ms instead of the desired 15 ms.

I'm thinking the code could be changed to something like this:

```rust
// Wait until 16ms have passed
let diff = time_start.elapsed();
let frame_time = Duration::from_millis(16);
if diff < frame_time {
    thread::sleep(frame_time - diff);
}
```

**Comment by fschutt** [comment]
Yep, that's right, thanks for catching this. It should be `frame_time - diff`, not just `diff`.
