### ISSUE TITLE
Update The installation wiki

### ISSUE THREAD

**Issue by o0Ignition0o** [maps4print/azul#64]
Hi and thanks for providing a great starter wiki :) 

I noticed azul 0.1.0 is available on crates.io, so I wanted to submit a patch to update the wiki, but I can't figure out a way to submit it.

If there's a way to submit it please let me know, else here's the patch :)

```diff --git a/Installation.md b/Installation.md
index 6559042..0bfe92c 100644
--- a/Installation.md
+++ b/Installation.md
@@ -82,15 +82,9 @@ lines beneath the [dependencies] section:
 
 ```toml
 [dependencies]
-azul = { git = "https://github.com/maps4print/azul" }
+azul = "0.1.0"
 ```
 
-**WARNING: ** Azul has not yet been released on crates.io, therefore,
-there is no package available. This guide will be updated once the
-first stable version releases. It is recommended to version-lock your
-dependency with `{ git = "...", rev = "the_last_commit_hash" }`, so
-that you know which commit you are using.
-
 This will pull in the latest stable version of azul. Open the
 `/my_first_azul_app/src/main.rs` file and edit it to look like this:
```

The preview is a bit  ugly since github parses the diff, I basically changed the git pointer to 0.1.0 and removed the warning ^^'

**Comment by fschutt** [comment]
Yeah, but it's not a really release" - I've just reserved the name. There is no code on crates.io, just an empty crate as a placeholder. So the installation section is still valid. Trust me, I won't forget to update the wiki when it actually releases (somewhere around December).
