### ISSUE TITLE
Panic running guide example on OSX

### ISSUE THREAD

**Issue by jjl** [maps4print/azul#73]
## Description

Crash attempting to compile the code from the guide

## Version / OS

* azul version: master
* Operating system: Mac OS 10.13.6

## Steps to Reproduce

Compile this code (from the guide):
```
extern crate azul;

use azul::prelude::*;

struct AppModel {
}
impl Layout for AppModel {
    fn layout(&self, _: WindowInfo<Self>) -> Dom<Self> {
        Dom::new(NodeType::Div)
    }
}

fn main() {
    let app = App::new(AppModel { }, AppConfig::default());
    let window = Window::new(WindowCreateOptions::default(), Css::native()).unwrap();
    app.run(window).unwrap();
}
```

## Expected Behavior

Shows a window

## Actual Behavior
```
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/james/.cargo/registry/src/github.com-1ecc6299db9ec823/azul_glium-0.22.0/src/context/mod.rs at line 644 in thread main

Error information:
assertion failed: backend.is_current()

Backtrace:
```

## Additional Information

Similar symptoms to #18, but that has a backtrace and appears in different code.

Happy to help debug, a mac is my main environment right now.

**Comment by fschutt** [comment]
Yeah, this is probably the same as in https://github.com/maps4print/azul/issues/50#issuecomment-443837592. The real problem is that there is no backtrace anymore, which happened after upgrading glium. A similar error happens on Wayland (I did disable backtraces in glium because historically they've not been very useful). 

Not sure if this is also related to https://github.com/servo/webrender/pull/3318, but I can't see any checks for the OpenGL context. The line that crashes is here: https://github.com/fschutt/glium/blob/cda2cc0229f430baa72b49a3e407c153221b3c8d/src/context/mod.rs#L645, however, since the lines (make_current() and is_current()) are directly after each other, this may be a caching issue with glium (happens too often, sadly).

Can you run it in release mode and see if there's any output?

**Comment by jjl** [comment]
In release mode, I get a blank window!

**Comment by sombrastudios** [comment]
@jjl the very same thing happened to me. It's and known and open bug. Take a look at #5 for more Information

**Comment by user345987** [comment]
I have exactly the same problem on macos. 
If I change the dependency `azul_glium` to `glium` with the same version `0.22.0`, it works on debug build. Is this a bug in `azul_glium`?

**Comment by 7sDream** [comment]
Maybe I meet the same issue, but I can see the backtrace:

```
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: /Users/7sdream/.cargo/registry/src/github.com-1ecc6299db9ec823/azul_glium-0.22.0/src/context/mod.rs at line 644 in thread main

Error information:
assertion failed: backend.is_current()

Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:87
core::ops::function::Fn::call @ function.rs:78
std::panicking::rust_panic_with_hook @ panicking.rs:480
std::panicking::begin_panic @ panicking.rs:410
<azul_glium::context::Context as azul_glium::ContextExt>::make_current @ mod.rs:644
azul_glium::context::Context::new @ mod.rs:221
azul_glium::backend::glutin::Display::new_inner @ mod.rs:113
azul_glium::backend::glutin::Display::with_debug @ mod.rs:92
<azul::window::Window<T>>::new @ window.rs:777
counter::main @ main.rs:13
std::rt::lang_start::{{closure}} @ rt.rs:74
std::panicking::try::do_call @ panicking.rs:310
 @ lib.rs:102
std::rt::lang_start_internal @ panicking.rs:289
std::rt::lang_start @ rt.rs:74
```

Any help?

**Comment by fschutt** [comment]
Well, this has been "fixed" by simply removing that line. I don't know why this line was there, but I've gotten reports that it seems to work fine without it. So this was "fixed" in https://github.com/maps4print/azul/commit/60df3d6114ade02273cadcdc1d54a98c60825c15 - should work now.
