### ISSUE TITLE
Helloworld broken

### ISSUE THREAD

**Issue by BearzRobotics** [maps4print/azul#8]
## Description
The hello world program on the website won't compile.

## Version / OS
* azul version: v0.1.0
* Operating system: Solus 

## Steps to Reproduce
Take the example helloworld program on the website and try to compile it.

## Expected Behavior
For it to compile

## Actual Behavior
It doesn't compile

## Solution
I found the answer going through the debug example. at the line:
       let mut app = App::new(MyDataModel { counter: 0 });
it needs to be:
       let mut app = App::new(MyDataModel { counter: 0 }, AppConfig::default());
This makes the helloworld program compile and would give people coming to this Gui framework a better experanice.

**Comment by fschutt** [comment]
Oh, the one on the website - yes, that happens a lot, the documentation is lacking. Right now the website is more in a beta stage - the APIs change so quickly that they'd become outdated almost immediately.

Thanks for the issue, should be fixed now.
