### ISSUE TITLE
winit-0.18.0 error[E0004]

### ISSUE THREAD

**Issue by DeepInThought** [maps4print/azul#86]
## Description

When running through the installation [creating-a-new-project](https://github.com/maps4print/azul/wiki/Installation#creating-a-new-project) and executing the `cargo run` command I receiving the following error: 

> error[E0004]: non-exhaustive patterns: `Shape { .. }` and `Orientation { .. }` not covered
  --> /home/deepit/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/touch.rs:30:19
   |
30 |             match evt {
   |                   ^^^ patterns `Shape { .. }` and `Orientation { .. }` not covered
>
>error: aborting due to previous error
>
> 
> For more information about this error, try `rustc --explain E0004`.
> error: Could not compile `winit`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed

## Version / OS

* azul version:
azul = { git = "https://github.com/maps4print/azul", rev = "864de10a0a7cfbe88a9719a5c7070d2323a58de3" }

* Operating system:
Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Windowing system (X11 or Wayland, Linux only):
X11

## Steps to Reproduce

```
cargo new --bin my_first_azul_app
cd my_first_azul_app
cargo run
```

## Expected Behavior
Cargo run without errors.

## Actual Behavior
`error[E0004]: non-exhaustive patterns: `Shape { .. }` and `Orientation { .. }` not covered
  --> /home/deepit/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/touch.rs:30:19
   |
30 |             match evt {
   |                   ^^^ patterns `Shape { .. }` and `Orientation { .. }` not covered

error: aborting due to previous error

For more information about this error, try `rustc --explain E0004`.
error: Could not compile `winit`.
warning: build failed, waiting for other jobs to finish...
error: build failed`

## Additional Information

I found a workaround by adding `wayland-client = "=0.21.7"` via

https://github.com/amethyst/amethyst/issues/1324

**Comment by fschutt** [comment]
See https://github.com/Smithay/wayland-rs/issues/221 - wayland-client broke semver. This should be fixed permanently when azul switches to a monorepo.
